<?php

return [
    [
        "name" => "Frodo Baggins",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Frodo_Baggins",
        "race" => "Hobbit",
        "birth" => "22 September, TA 2968",
        "gender" => "Male",
        "death" => null,
        "hair" => "Dark brown",
        "height" => "1.22 m",
        "realm" => "The Shire",
        "spouse" => null,
    ],
    [
        "name" => "Samwise Gamgee",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Samwise_Gamgee",
        "race" => "Hobbit",
        "birth" => "6 April, TA 2980",
        "gender" => "Male",
        "death" => null,
        "hair" => "Sandy",
        "height" => "1.22 m",
        "realm" => "The Shire",
        "spouse" => "Rosie Cotton",
    ],
    [
        "name" => "Aragorn",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Aragorn",
        "race" => "Human",
        "birth" => "1 March, TA 2931",
        "gender" => "Male",
        "death" => "FO 120",
        "hair" => "Dark",
        "height" => "1.98 m",
        "realm" => "Gondor",
        "spouse" => "Arwen",
    ],
    [
        "name" => "Gandalf",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Gandalf",
        "race" => "Maia",
        "birth" => "Before the shaping of Arda",
        "gender" => "Male",
        "death" => null,
        "hair" => "Grey, later White",
        "height" => "1.75 m",
        "realm" => null,
        "spouse" => null,
    ],
    [
        "name" => "Legolas",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Legolas",
        "race" => "Elf",
        "birth" => "TA 87",
        "gender" => "Male",
        "death" => null,
        "hair" => "Blond",
        "height" => "1.83 m",
        "realm" => "Woodland Realm",
        "spouse" => null,
    ],
    [
        "name" => "Gimli",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Gimli",
        "race" => "Dwarf",
        "birth" => "TA 2879",
        "gender" => "Male",
        "death" => null,
        "hair" => "Red",
        "height" => "1.37 m",
        "realm" => "Erebor",
        "spouse" => null,
    ],
    [
        "name" => "Arwen",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Arwen",
        "race" => "Half-elven",
        "birth" => "TA 241",
        "gender" => "Female",
        "death" => "FO 121",
        "hair" => "Dark brown",
        "height" => "1.68 m",
        "realm" => "Rivendell",
        "spouse" => "Aragorn",
    ],
    [
        "name" => "Boromir",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Boromir",
        "race" => "Human",
        "birth" => "TA 2978",
        "gender" => "Male",
        "death" => "26 February, TA 3019",
        "hair" => "Dark",
        "height" => "1.93 m",
        "realm" => "Gondor",
        "spouse" => null,
    ],
    [
        "name" => "Galadriel",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Galadriel",
        "race" => "Elf",
        "birth" => "YT 1362",
        "gender" => "Female",
        "death" => null,
        "hair" => "Golden",
        "height" => "1.88 m",
        "realm" => "Lothlórien",
        "spouse" => "Celeborn",
    ],
    [
        "name" => "Saruman",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Saruman",
        "race" => "Maia",
        "birth" => "Before the shaping of Arda",
        "gender" => "Male",
        "death" => "3 November, TA 3019",
        "hair" => "White",
        "height" => "1.88 m",
        "realm" => "Isengard",
        "spouse" => null,
    ],
    [
        "name" => "Éowyn",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Éowyn",
        "race" => "Human",
        "birth" => "TA 2995",
        "gender" => "Female",
        "death" => null,
        "hair" => "Blonde",
        "height" => "1.80 m",
        "realm" => "Rohan",
        "spouse" => "Faramir",
    ],
    [
        "name" => "Faramir",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Faramir",
        "race" => "Human",
        "birth" => "TA 2983",
        "gender" => "Male",
        "death" => null,
        "hair" => "Dark",
        "height" => "1.83 m",
        "realm" => "Gondor",
        "spouse" => "Éowyn",
    ],
    [
        "name" => "Elrond",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Elrond",
        "race" => "Half-elven",
        "birth" => "FA 532",
        "gender" => "Male",
        "death" => null,
        "hair" => "Dark",
        "height" => "1.95 m",
        "realm" => "Rivendell",
        "spouse" => "Celebrían",
    ],
    [
        "name" => "Gollum",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Gollum",
        "race" => "Hobbit",
        "birth" => "TA 2430",
        "gender" => "Male",
        "death" => "25 March, TA 3019",
        "hair" => "None",
        "height" => "1.40 m",
        "realm" => null,
        "spouse" => null,
    ],
    [
        "name" => "Bilbo Baggins",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Bilbo_Baggins",
        "race" => "Hobbit",
        "birth" => "22 September, TA 2890",
        "gender" => "Male",
        "death" => "29 September, TA 3021",
        "hair" => "Brown",
        "height" => "1.22 m",
        "realm" => "The Shire",
        "spouse" => null,
    ],
    [
        "name" => "Peregrin Took",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Peregrin_Took",
        "race" => "Hobbit",
        "birth" => "TA 2990",
        "gender" => "Male",
        "death" => "FO 64",
        "hair" => "Brown",
        "height" => "1.22 m",
        "realm" => "The Shire",
        "spouse" => "Diamond of Long Cleeve",
    ],
    [
        "name" => "Meriadoc Brandybuck",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Meriadoc_Brandybuck",
        "race" => "Hobbit",
        "birth" => "TA 2982",
        "gender" => "Male",
        "death" => "FO 64",
        "hair" => "Brown",
        "height" => "1.22 m",
        "realm" => "The Shire",
        "spouse" => "Estella Bolger",
    ],
    [
        "name" => "Treebeard",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Treebeard",
        "race" => "Ent",
        "birth" => "Before the Great Darkness",
        "gender" => "Male",
        "death" => null,
        "hair" => "Green and Grey",
        "height" => "4.5 m",
        "realm" => "Fangorn Forest",
        "spouse" => null,
    ],
    [
        "name" => "Théoden",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Théoden",
        "race" => "Human",
        "birth" => "TA 2948",
        "gender" => "Male",
        "death" => "15 March, TA 3019",
        "hair" => "Grey",
        "height" => "1.88 m",
        "realm" => "Rohan",
        "spouse" => "Elfhild",
    ],
    [
        "name" => "Éomer",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Éomer",
        "race" => "Human",
        "birth" => "TA 2991",
        "gender" => "Male",
        "death" => "FO 63",
        "hair" => "Blond",
        "height" => "1.93 m",
        "realm" => "Rohan",
        "spouse" => "Lothíriel",
    ],
    [
        "name" => "Denethor II",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Denethor_II",
        "race" => "Human",
        "birth" => "TA 2930",
        "gender" => "Male",
        "death" => "15 March, TA 3019",
        "hair" => "Black",
        "height" => "1.93 m",
        "realm" => "Gondor",
        "spouse" => "Finduilas",
    ],
    [
        "name" => "Glorfindel",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Glorfindel",
        "race" => "Elf",
        "birth" => "YT",
        "gender" => "Male",
        "death" => null,
        "hair" => "Golden",
        "height" => "1.93 m",
        "realm" => "Rivendell",
        "spouse" => null,
    ],
    [
        "name" => "Gríma Wormtongue",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Gríma_Wormtongue",
        "race" => "Human",
        "birth" => "TA",
        "gender" => "Male",
        "death" => "3 November, TA 3019",
        "hair" => "Black",
        "height" => "1.75 m",
        "realm" => "Rohan",
        "spouse" => null,
    ],
    [
        "name" => "Balin",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Balin",
        "race" => "Dwarf",
        "birth" => "TA 2763",
        "gender" => "Male",
        "death" => "TA 2994",
        "hair" => "White",
        "height" => "1.35 m",
        "realm" => "Erebor",
        "spouse" => null,
    ],
    [
        "name" => "Bard the Bowman",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Bard_the_Bowman",
        "race" => "Human",
        "birth" => "TA",
        "gender" => "Male",
        "death" => "TA 2977",
        "hair" => "Black",
        "height" => "1.93 m",
        "realm" => "Dale",
        "spouse" => null,
    ],
    [
        "name" => "Thranduil",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Thranduil",
        "race" => "Elf",
        "birth" => "YT",
        "gender" => "Male",
        "death" => null,
        "hair" => "Blonde",
        "height" => "1.95 m",
        "realm" => "Woodland Realm",
        "spouse" => null,
    ],
    [
        "name" => "Radagast",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Radagast",
        "race" => "Maia",
        "birth" => "Before the shaping of Arda",
        "gender" => "Male",
        "death" => null,
        "hair" => "Brown",
        "height" => "1.75 m",
        "realm" => "Rhosgobel",
        "spouse" => null,
    ],
    [
        "name" => "Elendil",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Elendil",
        "race" => "Human",
        "birth" => "SA 3119",
        "gender" => "Male",
        "death" => "SA 3441",
        "hair" => "Black",
        "height" => "2.40 m",
        "realm" => "Arnor",
        "spouse" => null,
    ],
    [
        "name" => "Isildur",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Isildur",
        "race" => "Human",
        "birth" => "SA 3209",
        "gender" => "Male",
        "death" => "TA 2",
        "hair" => "Black",
        "height" => "2.10 m",
        "realm" => "Gondor",
        "spouse" => null,
    ],
    [
        "name" => "Gothmog",
        "wikiUrl" => "https://lotr.fandom.com/wiki/Gothmog_(Lieutenant_of_Minas_Morgul)",
        "race" => "Orc",
        "birth" => "Unknown",
        "gender" => "Male",
        "death" => "TA 3019",
        "hair" => "None",
        "height" => "1.85 m",
        "realm" => "Minas Morgul",
        "spouse" => null,
    ],
];
