<?php

return [
    [
        "name" => "Adanel",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Adanel",
        "race" => "Human",
        "birth" => null,
        "gender" => "Female",
        "death" => null,
        "hair" => null,
        "height" => null,
        "realm" => null,
        "spouse" => "Belemir"
    ],
    [
        "name" => "Adrahil I",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Adrahil_I",
        "race" => "Human",
        "birth" => "Before ,TA 1944",
        "gender" => "Male",
        "death" => "Late ,Third Age",
        "hair" => null,
        "height" => null,
        "realm" => null,
        "spouse" => null
    ],
    [
        "name" => "Adrahil II",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Adrahil_II",
        "race" => "Human",
        "birth" => "TA 2917",
        "gender" => "Male",
        "death" => "TA 3010",
        "hair" => null,
        "height" => null,
        "realm" => "Dol Amroth",
        "spouse" => null
    ],
    [
        "name" => "Aegnor",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Aegnor",
        "race" => "Elf",
        "birth" => "YT",
        "gender" => "Male",
        "death" => "First Age",
        "hair" => null,
        "height" => null,
        "realm" => null,
        "spouse" => null
    ],
    [
        "name" => "Aerin",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Aerin",
        "race" => "Human",
        "birth" => null,
        "gender" => "Female",
        "death" => null,
        "hair" => null,
        "height" => null,
        "realm" => null,
        "spouse" => "Brodda"
    ],
    [
        "name" => "Aldor",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Aldor",
        "race" => "Human",
        "birth" => null,
        "gender" => "Male",
        "death" => "TA 2645",
        "hair" => null,
        "height" => null,
        "realm" => "Rohan",
        "spouse" => null
    ],
    [
        "name" => "Amarië",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Amarië",
        "race" => "Elf",
        "birth" => null,
        "gender" => "Female",
        "death" => null,
        "hair" => null,
        "height" => null,
        "realm" => "Valinor",
        "spouse" => "Finrod"
    ],
    [
        "name" => "Amdír",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Amd%C3%ADr",
        "race" => "Elf",
        "birth" => null,
        "gender" => "Male",
        "death" => "TA 3434",
        "hair" => null,
        "height" => null,
        "realm" => "Lothlórien",
        "spouse" => null
    ],
    [
        "name" => "Amras",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Amras",
        "race" => "Elf",
        "birth" => "YT",
        "gender" => "Male",
        "death" => "First Age",
        "hair" => null,
        "height" => null,
        "realm" => null,
        "spouse" => null
    ],
    [
        "name" => "Amrod",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Amrod",
        "race" => "Elf",
        "birth" => "YT",
        "gender" => "Male",
        "death" => "First Age",
        "hair" => null,
        "height" => null,
        "realm" => null,
        "spouse" => null
    ],
    [
        "name" => "Anárion",
        "wikiUrl" => "http://lotr.wikia.com//wiki/An%C3%A1rion",
        "race" => "Human",
        "birth" => null,
        "gender" => "Male",
        "death" => "SA 3440",
        "hair" => null,
        "height" => null,
        "realm" => "Gondor",
        "spouse" => null
    ],
    [
        "name" => "Andróg",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Andr%C3%B3g",
        "race" => "Human",
        "birth" => null,
        "gender" => "Male",
        "death" => "First Age",
        "hair" => null,
        "height" => null,
        "realm" => null,
        "spouse" => null
    ],
    [
        "name" => "Angelimar",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Angelimar",
        "race" => "Human",
        "birth" => null,
        "gender" => "Male",
        "death" => null,
        "hair" => null,
        "height" => null,
        "realm" => "Gondor",
        "spouse" => null
    ],
    [
        "name" => "Angrod",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Angrod",
        "race" => "Elf",
        "birth" => "YT",
        "gender" => "Male",
        "death" => "First Age",
        "hair" => null,
        "height" => null,
        "realm" => null,
        "spouse" => null
    ],
    [
        "name" => "Annael",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Annael",
        "race" => "Elf",
        "birth" => null,
        "gender" => "Male",
        "death" => null,
        "hair" => null,
        "height" => null,
        "realm" => null,
        "spouse" => null
    ],
    [
        "name" => "Arantar",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Arantar",
        "race" => "Human",
        "birth" => null,
        "gender" => "Male",
        "death" => null,
        "hair" => null,
        "height" => null,
        "realm" => "Arnor",
        "spouse" => null
    ],
    [
        "name" => "Aranuir",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Aranuir",
        "race" => "Human",
        "birth" => null,
        "gender" => "Male",
        "death" => null,
        "hair" => null,
        "height" => null,
        "realm" => "Arnor",
        "spouse" => null
    ],
    [
        "name" => "Araphant",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Araphant",
        "race" => "Human",
        "birth" => null,
        "gender" => "Male",
        "death" => null,
        "hair" => null,
        "height" => null,
        "realm" => "Arnor",
        "spouse" => null
    ],
    [
        "name" => "Arassuil",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Arassuil",
        "race" => "Human",
        "birth" => null,
        "gender" => "Male",
        "death" => null,
        "hair" => null,
        "height" => null,
        "realm" => "Arnor",
        "spouse" => null
    ],
    [
        "name" => "Aratan",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Aratan",
        "race" => "Human",
        "birth" => null,
        "gender" => "Male",
        "death" => "SA 3440",
        "hair" => null,
        "height" => null,
        "realm" => "Gondor",
        "spouse" => null
    ],
    [
        "name" => "Arathorn I",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Arathorn_I",
        "race" => "Human",
        "birth" => null,
        "gender" => "Male",
        "death" => null,
        "hair" => null,
        "height" => null,
        "realm" => "Arnor",
        "spouse" => null
    ],
    [
        "name" => "Arathorn II",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Arathorn_II",
        "race" => "Human",
        "birth" => "TA 2873",
        "gender" => "Male",
        "death" => "TA 2933",
        "hair" => null,
        "height" => null,
        "realm" => null,
        "spouse" => "Gilraen"
    ],
    [
        "name" => "Argonui",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Argonui",
        "race" => "Human",
        "birth" => null,
        "gender" => "Male",
        "death" => "TA 2912",
        "hair" => null,
        "height" => null,
        "realm" => "Arnor",
        "spouse" => null
    ],
    [
        "name" => "Arod",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Arod",
        "race" => "Horse",
        "birth" => null,
        "gender" => "Male",
        "death" => null,
        "hair" => null,
        "height" => null,
        "realm" => null,
        "spouse" => null
    ],
    [
        "name" => "Arwen",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Arwen",
        "race" => "Half-elven",
        "birth" => "TA 241",
        "gender" => "Female",
        "death" => "FO 121",
        "hair" => "Dark",
        "height" => null,
        "realm" => "Rivendell",
        "spouse" => "Aragorn II Elessar"
    ],
    [
        "name" => "Asfaloth",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Asfaloth",
        "race" => "Horse",
        "birth" => null,
        "gender" => "Male",
        "death" => null,
        "hair" => null,
        "height" => null,
        "realm" => null,
        "spouse" => null
    ],
    [
        "name" => "Balin",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Balin",
        "race" => "Dwarf",
        "birth" => "TA 2763",
        "gender" => "Male",
        "death" => "TA 2994",
        "hair" => null,
        "height" => null,
        "realm" => null,
        "spouse" => null
    ],
    [
        "name" => "Baragund",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Baragund",
        "race" => "Human",
        "birth" => "FA 421",
        "gender" => "Male",
        "death" => "FA 460",
        "hair" => null,
        "height" => null,
        "realm" => null,
        "spouse" => "Unnamed wife"
    ],
    [
        "name" => "Barahir",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Barahir",
        "race" => "Human",
        "birth" => "TA 262",
        "gender" => "Male",
        "death" => "TA 300",
        "hair" => null,
        "height" => null,
        "realm" => null,
        "spouse" => null
    ],
    [
        "name" => "Belecthor II",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Belecthor_II",
        "race" => "Human",
        "birth" => "TA 2872",
        "gender" => "Male",
        "death" => "TA 2976",
        "hair" => null,
        "height" => null,
        "realm" => "Gondor",
        "spouse" => null
    ],
    [
        "name" => "Beregond",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Beregond",
        "race" => "Human",
        "birth" => null,
        "gender" => "Male",
        "death" => null,
        "hair" => null,
        "height" => null,
        "realm" => "Gondor",
        "spouse" => null
    ],
    [
        "name" => "Bergil",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Bergil",
        "race" => "Human",
        "birth" => null,
        "gender" => "Male",
        "death" => null,
        "hair" => null,
        "height" => null,
        "realm" => "Gondor",
        "spouse" => null
    ],
    [
        "name" => "Borin",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Borin",
        "race" => "Dwarf",
        "birth" => "TA 2450",
        "gender" => "Male",
        "death" => "TA 2711",
        "hair" => null,
        "height" => null,
        "realm" => null,
        "spouse" => null
    ],
    [
        "name" => "Denethor I",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Denethor_I",
        "race" => "Human",
        "birth" => "TA 2375",
        "gender" => "Male",
        "death" => "TA 2477",
        "hair" => null,
        "height" => null,
        "realm" => "Gondor",
        "spouse" => null
    ],
    [
        "name" => "Denethor II",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Denethor_II",
        "race" => "Human",
        "birth" => "TA 2930",
        "gender" => "Male",
        "death" => "TA 3019",
        "hair" => null,
        "height" => null,
        "realm" => "Gondor",
        "spouse" => "Finduilas"
    ],
    [
        "name" => "Duilin",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Duilin",
        "race" => "Human",
        "birth" => null,
        "gender" => "Male",
        "death" => "TA 3019",
        "hair" => null,
        "height" => null,
        "realm" => "Gondor",
        "spouse" => null
    ],
    [
        "name" => "Durin I",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Durin_I",
        "race" => "Dwarf",
        "birth" => null,
        "gender" => "Male",
        "death" => null,
        "hair" => null,
        "height" => null,
        "realm" => "Khazad-dûm",
        "spouse" => null
    ],
    [
        "name" => "Durin VI",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Durin_VI",
        "race" => "Dwarf",
        "birth" => "TA 1731",
        "gender" => "Male",
        "death" => "TA 1980",
        "hair" => null,
        "height" => null,
        "realm" => "Khazad-dûm",
        "spouse" => null
    ],
    [
        "name" => "Earendil",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Earendil",
        "race" => "Half-elven",
        "birth" => "FA 503",
        "gender" => "Male",
        "death" => null,
        "hair" => null,
        "height" => null,
        "realm" => null,
        "spouse" => "Elwing"
    ],
    [
        "name" => "Eärnil I",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Eärnil_I",
        "race" => "Human",
        "birth" => "TA 736",
        "gender" => "Male",
        "death" => "TA 936",
        "hair" => null,
        "height" => null,
        "realm" => "Gondor",
        "spouse" => null
    ],
    [
        "name" => "Eärnil II",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Eärnil_II",
        "race" => "Human",
        "birth" => "TA 1883",
        "gender" => "Male",
        "death" => "TA 2043",
        "hair" => null,
        "height" => null,
        "realm" => "Gondor",
        "spouse" => null
    ],
    [
        "name" => "Eärnur",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Eärnur",
        "race" => "Human",
        "birth" => "TA 1928",
        "gender" => "Male",
        "death" => "TA 2050",
        "hair" => null,
        "height" => null,
        "realm" => "Gondor",
        "spouse" => null
    ],
    [
        "name" => "Ecthelion II",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Ecthelion_II",
        "race" => "Human",
        "birth" => "TA 2886",
        "gender" => "Male",
        "death" => "TA 2984",
        "hair" => null,
        "height" => null,
        "realm" => "Gondor",
        "spouse" => null
    ],
    [
        "name" => "Egalmoth",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Egalmoth",
        "race" => "Elf",
        "birth" => "YT",
        "gender" => "Male",
        "death" => "FA 511",
        "hair" => null,
        "height" => null,
        "realm" => "Gondolin",
        "spouse" => null
    ],
    [
        "name" => "Eilinel",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Eilinel",
        "race" => "Human",
        "birth" => null,
        "gender" => "Female",
        "death" => "FA 455",
        "hair" => null,
        "height" => null,
        "realm" => null,
        "spouse" => "Gorlim"
    ],
    [
        "name" => "Elendil",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Elendil",
        "race" => "Human",
        "birth" => "SA 3119",
        "gender" => "Male",
        "death" => "SA 3441",
        "hair" => null,
        "height" => "Tall",
        "realm" => "Arnor",
        "spouse" => null
    ],
    [
        "name" => "Elendur",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Elendur",
        "race" => "Human",
        "birth" => null,
        "gender" => "Male",
        "death" => "SA 3440",
        "hair" => null,
        "height" => null,
        "realm" => "Arnor",
        "spouse" => null
    ],
    [
        "name" => "Elros",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Elros",
        "race" => "Half-elven",
        "birth" => "FA 525",
        "gender" => "Male",
        "death" => "SA 442",
        "hair" => null,
        "height" => null,
        "realm" => "Númenor",
        "spouse" => null
    ],
    [
        "name" => "Elrond",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Elrond",
        "race" => "Half-elven",
        "birth" => "FA 532",
        "gender" => "Male",
        "death" => "FO 120",
        "hair" => "Dark",
        "height" => "Tall",
        "realm" => "Rivendell",
        "spouse" => "Celebrían"
    ],
    [
        "name" => "Elwing",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Elwing",
        "race" => "Half-elven",
        "birth" => "FA 503",
        "gender" => "Female",
        "death" => null,
        "hair" => null,
        "height" => null,
        "realm" => null,
        "spouse" => "Eärendil"
    ],
    [
        "name" => "Eradan",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Eradan",
        "race" => "Human",
        "birth" => null,
        "gender" => "Male",
        "death" => null,
        "hair" => null,
        "height" => null,
        "realm" => null,
        "spouse" => null
    ],
    [
        "name" => "Fëanor",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Fëanor",
        "race" => "Elf",
        "birth" => "YT",
        "gender" => "Male",
        "death" => "FA 499",
        "hair" => "Dark",
        "height" => null,
        "realm" => "Valinor",
        "spouse" => "Nerdanel"
    ],
    [
        "name" => "Fingolfin",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Fingolfin",
        "race" => "Elf",
        "birth" => "YT",
        "gender" => "Male",
        "death" => "FA 455",
        "hair" => "Dark",
        "height" => "Tall",
        "realm" => "Hithlum",
        "spouse" => "Anairë"
    ],
    [
        "name" => "Finwë",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Finwë",
        "race" => "Elf",
        "birth" => "YT",
        "gender" => "Male",
        "death" => "YT 1495",
        "hair" => "Dark",
        "height" => "Tall",
        "realm" => "Tirion",
        "spouse" => "Míriel"
    ],
    [
        "name" => "Galadriel",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Galadriel",
        "race" => "Elf",
        "birth" => "YT 1362",
        "gender" => "Female",
        "death" => "FO 3021",
        "hair" => "Golden",
        "height" => "Tall",
        "realm" => "Lothlórien",
        "spouse" => "Celeborn"
    ],
    [
        "name" => "Gimli",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Gimli",
        "race" => "Dwarf",
        "birth" => "TA 2879",
        "gender" => "Male",
        "death" => "FO 120",
        "hair" => "Dark",
        "height" => "Short",
        "realm" => "Erebor",
        "spouse" => null
    ],
    [
        "name" => "Gorlim",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Gorlim",
        "race" => "Human",
        "birth" => null,
        "gender" => "Male",
        "death" => "FA 465",
        "hair" => null,
        "height" => null,
        "realm" => null,
        "spouse" => "Eilinel"
    ],
    [
        "name" => "Gwaihir",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Gwaihir",
        "race" => "Great Eagle",
        "birth" => null,
        "gender" => "Male",
        "death" => null,
        "hair" => null,
        "height" => null,
        "realm" => null,
        "spouse" => null
    ],
    [
        "name" => "Haldir",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Haldir",
        "race" => "Elf",
        "birth" => null,
        "gender" => "Male",
        "death" => null,
        "hair" => "Golden",
        "height" => null,
        "realm" => "Lothlórien",
        "spouse" => null
    ],
    [
        "name" => "Isildur",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Isildur",
        "race" => "Human",
        "birth" => "SA 3209",
        "gender" => "Male",
        "death" => "TA 2",
        "hair" => null,
        "height" => null,
        "realm" => "Gondor",
        "spouse" => null
    ],
    [
        "name" => "Legolas",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Legolas",
        "race" => "Elf",
        "birth" => null,
        "gender" => "Male",
        "death" => null,
        "hair" => "Blond",
        "height" => null,
        "realm" => "Woodland Realm",
        "spouse" => null
    ],
    [
        "name" => "Lúthien",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Lúthien",
        "race" => "Half-elven",
        "birth" => "YT",
        "gender" => "Female",
        "death" => "FA 503",
        "hair" => "Dark",
        "height" => null,
        "realm" => null,
        "spouse" => "Beren"
    ],
    [
        "name" => "Sauron",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Sauron",
        "race" => "Maia",
        "birth" => "Before Time",
        "gender" => "Male",
        "death" => "TA 3019",
        "hair" => null,
        "height" => null,
        "realm" => "Mordor",
        "spouse" => null
    ],
    [
        "name" => "Théoden",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Théoden",
        "race" => "Human",
        "birth" => "TA 2948",
        "gender" => "Male",
        "death" => "TA 3019",
        "hair" => null,
        "height" => null,
        "realm" => "Rohan",
        "spouse" => "Elfhild"
    ],
    [
        "name" => "Thorin II Oakenshield",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Thorin_II_Oakenshield",
        "race" => "Dwarf",
        "birth" => "TA 2746",
        "gender" => "Male",
        "death" => "TA 2941",
        "hair" => null,
        "height" => null,
        "realm" => "Erebor",
        "spouse" => null
    ],
    [
        "name" => "Túrin Turambar",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Túrin_Turambar",
        "race" => "Human",
        "birth" => "FA 464",
        "gender" => "Male",
        "death" => "FA 499",
        "hair" => "Dark",
        "height" => null,
        "realm" => null,
        "spouse" => "Níniel"
    ],
    [
        "name" => "Yavanna",
        "wikiUrl" => "http://lotr.wikia.com//wiki/Yavanna",
        "race" => "Vala",
        "birth" => "Before Time",
        "gender" => "Female",
        "death" => null,
        "hair" => "Dark",
        "height" => null,
        "realm" => "Valinor",
        "spouse" => "Aulë"
    ]
];
